### ISSUE TITLE
Redesign json_scanf format strings

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#172] opened 2021-01-30 21:06 UTC
We reuse the format strings of scanf for extracting json values. The upside is we don't have to educate our users about our format strings, but the downside is our format strings do not behavior the same as scanf's format strings, believing in that they are the same as scanf's ones will cause bugs.

we use this following format strings:
```
%s, %.*s, %?s
%d, %ld
%f, %lf
%b
%F
%T
```

The biggest problem is  %s in scanf will load the raw char bytes, but json_scanf load and escape the raw char bytes according the JSON RFC. 

In order to avoid any confusion, I propose that we define a complete different set of format strings. 
```
%JStr, %.*JStr, %?JStr     // load and unescape the raw char bytes according to JSON RFC
%RStr, %.*RStr, %?RStr  // load the raw char bytes
%JInt32, %JInt64
%JFloat, %JDouble
%JBool
%JFunPtr
%JSizedBuffer
```

**Comment by mlite** [comment] 2021-01-30 21:13
The same format strings can be used for json_printf
```
%JStr, %.*JStr      // escape and print the escaped string
%RStr, %.*RStr     // print the raw string
%JInt32, %JInt64  
%JFloat, %JDouble
%JBool
%JFunPtr
%JSizedBuffer

**Comment by mlite** [comment] 2021-01-30 21:15
@LucasMull can you please take time to think about this proposal?

**Comment by LucasMull** [comment] 2021-01-30 21:46
These concerns are very reasonable, I'm all for it!

**Comment by mlite** [comment] 2021-01-31 02:38
> These concerns are very reasonable, I'm all for these changes!
what do you think about the choice of the format strings?  Here is another proposal:

```
#js, #.*js, #?js     
#s, #.*s     
#d, #ld
#f, #lf
#b
#p
#sized_buffer
```

**Comment by LucasMull** [comment] 2021-01-31 14:02
> The same format strings can be used for json_printf
> 
> ```
> 
> %JStr, %.*JStr      // escape and print the escaped string
> 
> %RStr, %.*RStr     // print the raw string
> 
> %JInt32, %JInt64  
> 
> %JFloat, %JDouble
> 
> %JBool
> 
> %JFunPtr
> 
> %JSizedBuffer
> 
> 

I think I prefer this one. It has the benefit of being its own thing, avoiding error that might be caused by the user assuming some functionalities to be identical to printf/scanf.

**Comment by mlite** [comment] 2021-01-31 18:26
the benefit of using a different leading character `#` is to make error detection much easier. 

if a user accidentally mixed up `scanf/printf` format strings,  we can easily detect and report them.  the latter design will significantly reduce usage errors.  Another benefit is the letter designated type are still similar to their counter parts in scanf/printf

**Comment by mlite** [comment] 2021-02-09 02:33
We need to seriously think about how to redesign this because the situations that json_scanf/printf need to handle is much more complex than the situation scanf/printf need to handle. 

each (key, value) type can be a combination of the following states:

1.  exist
2.  don't exist
3.  is nullable
4.  is not nullable

                            exist                      not exist                     nullable          not nullable
exist                                                                                         X                     X
not exist                                                                                   X                   
nullable                X                              X
not nullable          X

**Comment by mlite** [comment] 2021-02-09 02:35
I want to repurpose `?` for nullable, and  %.s for a value whose size is unknown at compile time.

**Comment by mlite** [comment] 2021-02-09 02:43
@LucasMull if you agree with the design,  I will make the change.

**Comment by mlite** [comment] 2021-02-09 02:44
@LucasMull we need to seriously consider using different leading char such as `#` to denote the format strings, as they are very different from `scanf/printf`

**Comment by LucasMull** [comment] 2021-02-09 14:11
> We need to seriously think about how to redesign this because the situations that json_scanf/printf need to handle is much more complex than the situation scanf/printf need to handle.
> 
> each (key, value) type can be a combination of the following states:
> 
> 1. exist
> 2. don't exist
> 3. is nullable
> 4. is not nullable
> 5. value's size is known at compile time
> 6. value's size is unknown at compile time
> 
> ```
>                        exist                      not exist                     nullable          not nullable
> exist                                                                                    X                     X
> not exist                                                                              X                   
> nullable                X                           X
> not nullable          X                      
> ```

Understood, adding this explanation to the json-scanf.h as a comment would be really great.

**Comment by LucasMull** [comment] 2021-02-09 14:12
> @LucasMull if you agree with the design, I will make the change.

Yeah totally!

**Comment by LucasMull** [comment] 2021-02-09 14:14
> @LucasMull we need to seriously consider using different leading char such as `#` to denote the format strings, as they are very different from the one used in `scanf/printf`. The downside is we need to write a documentation to explain how they can be used.

I didn't see the benefit before, but we already had a case of a contributor attempting to map our json-scanf specific specifiers to that of scanf and having some difficulties because of this. I agree, changing to `#` would be really helpful on making a distinction.

**Comment by mlite** [comment] 2021-02-09 17:45
I will add '#' as the alternative prefixing, and keep '%' so we have time to manage the transition. 

`#s?` will be the format string to handle a nullable string

**Comment by mlite** [comment] 2021-02-09 18:19
@LucasMull   I think $ as the start symbol is better than `#` as  $ is also used to Javascript template literals: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

`#` is more often used to start a comment in shell scripts.

**Comment by mlite** [comment] 2021-02-09 18:27
Perhaps, we can just use `:`  as the starting char
```
json_scanf (.., "[key]:s",  ...)
json_printf (..., "[key]:s", ...)
```

It matches json syntax even better.

**Comment by LucasMull** [comment] 2021-03-31 14:41
@mlite is this still a issue?

**Comment by mlite** [comment] 2021-03-31 19:19
It seems we have covered all cases, but I will keep this issue open.

**Comment by lcsmuller** [comment] 2021-10-30 14:53
Closing because it has been moved to `cee-utils` repository.

**Closed by lcsmuller** 2021-10-30 14:53 UTC
